language: python

matrix:
  include:
    - name: "Python 3.7"
      python: 3.7

script:
  - pip install setuptools==62.1.0
  - pip install importlib-metadata==0.20
  - python setup.py build install
  - python setup.py test

notifications:
  emails:
    - aokada@ncc.go.jp
  on_success: change
  on_failure: always

