name: UnitTest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install .
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint `find scripts -name "*.py"` --reports=y --disable='duplicate-code,trailing-whitespace,missing-module-docstring,missing-class-docstring,missing-function-docstring' | tee pylint.log
        python -m unittest tests.unit_test_germline_configure.py
        python -m unittest tests.unit_test_germline_samplesheet.py
        python -m unittest tests.unit_test_rna_configure.py
        python -m unittest tests.unit_test_rna_samplesheet.py
        python -m unittest tests.unit_test_somatic_configure.py
        python -m unittest tests.unit_test_somatic_samplesheet.py
        
